#!/bin/bash

# Exit on error
set -e

echo "🚀 Starting GitHub Pages deployment..."

# Check if we're in a git repository
if [ ! -d .git ]; then
    echo "❌ Error: Not a git repository"
    exit 1
fi

# Check if there are uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo "⚠️  Warning: You have uncommitted changes"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Ensure we're on main branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "⚠️  Warning: You're on branch '$CURRENT_BRANCH', not 'main'"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Build the Wasm production bundle BEFORE switching branches
echo "🏗️  Building production bundle..."
./gradlew :composeApp:buildWasmAsPwa --no-daemon

# Check if build was successful
BUILD_OUTPUT="composeApp/build/dist/wasmJs/productionExecutable"
if [ ! -d "$BUILD_OUTPUT" ]; then
    echo "❌ Error: Build failed - output directory not found"
    exit 1
fi

# Copy build output to a temporary directory outside the repo
echo "📦 Copying build output to temp directory..."
TEMP_DIR=$(mktemp -d)
cp -r "$BUILD_OUTPUT"/* "$TEMP_DIR/"

# Check if gh-pages branch exists
if git show-ref --verify --quiet refs/heads/gh-pages; then
    echo "📌 Checking out existing gh-pages branch..."
    git checkout gh-pages
    # Fetch latest from remote if it exists
    git fetch origin gh-pages 2>/dev/null || true
    git reset --hard origin/gh-pages 2>/dev/null || true
else
    echo "🌿 Creating new gh-pages branch..."
    git checkout --orphan gh-pages
    git rm -rf . 2>/dev/null || true
fi

# Remove all files except .git
echo "🧹 Cleaning branch..."
find . -maxdepth 1 ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} +

# Move build output from temp to root
echo "📦 Moving build output to root..."
cp -r "$TEMP_DIR"/* .

# Clean up temp directory
rm -rf "$TEMP_DIR"

# Add .nojekyll file (important for GitHub Pages)
echo "📄 Creating .nojekyll file..."
touch .nojekyll

# Create a simple README for gh-pages branch
cat > README.md << 'EOF'
# GitHub Pages Deployment

This branch contains the compiled WebAssembly application for GitHub Pages.

**Do not edit this branch manually!** It is automatically generated by the deployment script.

To update the deployment, run `./deploy-gh-pages.sh` from the `main` branch.
EOF

# Stage all changes
echo "📝 Staging changes..."
git add -A

# Commit
echo "💾 Committing..."
git commit -m "Deploy to GitHub Pages - $(date '+%Y-%m-%d %H:%M:%S')"

# Push to remote
echo "⬆️  Pushing to remote..."
git push origin gh-pages

# Switch back to main branch
echo "🔄 Switching back to main branch..."
git checkout main

echo "✅ Deployment complete!"
echo "🌐 Your site should be available at: https://<username>.github.io/<repository>/"
echo "📋 Make sure to configure GitHub Pages in repository settings to use the 'gh-pages' branch."